apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: default
  labels:
    app: flask-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: flask-api
        image: gcr.io/developing-stuff/flask-api:v0.0.2
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            value: "admin" 
          - name: POSTGRES_PASSWORD
            value: "admin"
          - name: POSTGRES_HOST
            value: "10.30.244.110"
          - name: POSTGRES_DB
            value: "databesos"
          - name: POSTGRES_PORT
            value: "5432"
        resources:
          limits:
            cpu: "0.1"
            memory: "64Mi"