apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: default
  labels:
    app: flask-api
spec:
  ports:
  - protocol: TCP
    port: 25443
  selector:
    app: flask-api
  type: LoadBalancer
  loadBalancerIP: ""