apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  namespace: default
  labels:
    app: flask-api
spec:
  selector:
    app: flask-api
  type: LoadBalancer
  ports:
  - name: tcp
    protocol: TCP
    port: 25443
  - name: http 
    port: 80 
    targetPort: 5000