version: '3'
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     DB_USER: admin
  #     DB_PASS: admin
  #     DB_HOST: db
  #     DB_NAME: suppliers
  #   depends_on:
  #     postgres:
  #       condition: service_started

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: localhost
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d suppliers"]
      interval: 10s
      timeout: 5s
      retries: 5