apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: POSTGRES_USER
            value: "{{ .Values.database.user }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.database.password }}"
          - name: POSTGRES_HOST
            value: "{{ .Values.database.host }}"
          - name: POSTGRES_DB
            value: "{{ .Values.database.dbname }}"
          - name: POSTGRES_PORT
            value: "{{ .Values.database.port }}"
        resources:
          limits:
            cpu: "{{ .Values.app.resources.cpu }}"
            memory: "{{ .Values.app.resources.memory }}"
