apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      protocol: TCP
      port: {{ .Values.service.tcpPort }}
      targetPort: {{ .Values.service.targetPort }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.targetPort }}
